"""
DivAi — Proposal Agent (Phase 5)

WHAT THIS AGENT DOES:
  Takes a selected solution card + intelligence report and generates
  a complete, professionally formatted technical project proposal.

  Outputs:
    - ProposalContent (structured data — all section text)
    - .docx file (built by document_builder.py)

WHERE IT FITS IN DIVAI:
  Layer 4 — Proposal Layer
  Fifth node in the LangGraph pipeline.
  Reads:  solutions, selected_solution_id, intelligence_report
  Writes: proposal_paths

CONCEPTS COVERED:
  - Structured document generation (schema → document)
  - Single vs multi-call LLM strategy for long content
  - Separating content generation from document rendering
  - Pydantic nested models for complex structured output
"""

import sys, os
sys.path.insert(0, os.path.join(os.path.dirname(__file__), ".."))

from dotenv import load_dotenv
from pydantic import BaseModel, Field
from langchain_openai import ChatOpenAI
from langchain_core.prompts import ChatPromptTemplate

load_dotenv()

OUTPUT_DIR = os.path.join(os.path.dirname(__file__), "../../output/proposals")


# ---------------------------------------------------------------------------
# Proposal Content Schema
# ---------------------------------------------------------------------------
# CONCEPT: Schema-Driven Document Generation
# Instead of asking Claude to write a freeform document, we define the
# exact structure we want BEFORE calling the LLM.
# Claude then fills in each field — we get predictable, parseable output.
# This is far more reliable than: "write me a proposal" → wall of text.
#
# Each field maps directly to a section in the Word document.
# The document_builder.py reads these fields and renders them with
# proper formatting (headings, bullets, tables).

class EffortRow(BaseModel):
    """One row in the effort estimate table."""
    role: str         # e.g. "Backend Engineer"
    phase: str        # e.g. "Phase 1"
    weeks: float      # e.g. 2.0
    hours: int        # e.g. 80
    notes: str        # e.g. "API development, agent setup"


class RiskItem(BaseModel):
    risk: str         # What could go wrong
    likelihood: str   # "Low" | "Medium" | "High"
    mitigation: str   # How we handle it


class ProposalContent(BaseModel):
    """
    The complete content for all 13 proposal sections.
    Every field is generated by Claude in a single structured output call.
    document_builder.py reads this and renders it into a Word document.
    """

    # Document metadata
    client_name: str = Field(description="Client company name inferred from the URL/report")
    project_title: str = Field(description="Compelling project name e.g. 'Project Pulse: AI Support Agent'")
    prepared_by: str = Field(default="DivAi Engineering", description="Agency name")

    # Section 1
    executive_summary: str = Field(
        description="3-4 sentences: business problem, proposed solution, key outcomes. "
                    "Written for a CEO/decision-maker, no jargon."
    )

    # Section 2
    problem_statement: str = Field(
        description="2-3 paragraphs: evidence from the website analysis that supports "
                    "the need for this solution. Reference specific signals observed."
    )

    # Section 3
    proposed_architecture: str = Field(
        description="2-3 paragraphs describing the system architecture at a high level. "
                    "Explain the components and how they interact. Include data flow."
    )

    # Section 4 — list of tech choices with brief rationale per item
    stack_choices: list[str] = Field(
        description="List of 'Technology: reason for choosing it' e.g. "
                    "'Claude API (claude-sonnet-4-6): Best-in-class reasoning for support queries'"
    )

    # Section 5
    phase_details: list[str] = Field(
        description="List of phases, each as 'Phase N (Week X-Y): what gets built and delivered'"
    )

    # Section 6
    api_specifications: str = Field(
        description="Key API endpoints this solution will expose or integrate with. "
                    "Format as a short paragraph or bullet list."
    )

    # Section 7
    security_compliance: str = Field(
        description="Auth strategy, data handling, relevant compliance notes (GDPR, PCI etc.)"
    )

    # Section 8
    testing_strategy: str = Field(
        description="Unit tests, integration tests, E2E tests — what gets tested and how."
    )

    # Section 9
    deployment_devops: str = Field(
        description="Infrastructure, CI/CD pipeline, environments (dev/staging/prod), monitoring."
    )

    # Section 10 — structured table data
    effort_rows: list[EffortRow] = Field(
        description="Effort breakdown by role and phase for the effort estimate table"
    )

    # Section 11
    investment_summary: str = Field(
        description="Cost range with assumptions. Reference effort estimates. "
                    "Keep ranges realistic (e.g. $X–$Y based on N weeks at standard rates)."
    )

    # Section 12
    risks: list[RiskItem] = Field(
        description="Top 3-5 risks with likelihood and mitigation strategy"
    )

    # Section 13
    next_steps: list[str] = Field(
        description="Numbered action items to move forward e.g. "
                    "'1. Schedule kick-off call to review requirements'"
    )


# ---------------------------------------------------------------------------
# Content generation
# ---------------------------------------------------------------------------

def generate_proposal_content(solution: dict, report: dict) -> ProposalContent:
    """
    Call Claude once to generate all proposal section content.

    CONCEPT: One Structured Call vs Many Small Calls
    --------------------------------------------------
    Option A (what we do): One call, Pydantic schema forces structure
      Pros: Fast (one API call), coherent (Claude sees everything at once)
      Cons: Long context = slightly higher token cost

    Option B: One call per section (13 calls)
      Pros: Each section gets full context window
      Cons: Slow, expensive, sections may contradict each other

    Option A is almost always the right choice for document generation.
    Claude's context window is large enough to handle this well.

    CONCEPT: Rich Context in the System Prompt
    We give Claude the full solution card AND the intelligence report.
    This grounds every section in real evidence — not generic proposal text.
    The problem_statement section can reference actual API endpoints observed.
    The architecture section references the real tech stack detected.
    This is what makes DivAi proposals genuinely useful vs generic templates.
    """
    llm = ChatOpenAI(
        model=os.getenv("LLM_MODEL", "anthropic/claude-sonnet-4-6"),
        temperature=0.4,
        api_key=os.getenv("OPENROUTER_API_KEY"),
        base_url="https://openrouter.ai/api/v1",
    )

    # CONCEPT: temperature=0.4 for document generation
    # Slightly higher than analysis (0.2-0.3) because proposals benefit from
    # more natural, varied language. Still low enough to be consistent and
    # professional — not creative writing territory (0.7+).

    structured_llm = llm.with_structured_output(ProposalContent)

    # Build context strings from the data
    tech = report.get("tech_stack", {})
    sol_stack = ", ".join(solution.get("stack", []))
    sol_phases = "\n".join(f"  {p}" for p in solution.get("phases", []))
    sol_risks = "\n".join(f"  - {r}" for r in solution.get("risks", []))
    sol_prereqs = "\n".join(f"  - {p}" for p in solution.get("prerequisites", []))

    report_context = f"""
CLIENT WEBSITE: {report.get('target_url')}
BUSINESS CATEGORY: {report.get('business_category')}
KEY FEATURES: {', '.join(report.get('key_features', []))}
INTEGRATIONS: {', '.join(report.get('integrations', []))}
TECH STACK: {tech.get('frontend_framework')} / {tech.get('language')}
DATA MODELS: {', '.join(report.get('data_models', []))}
AUTH PATTERN: {report.get('auth_pattern', {}).get('method')}
ANALYST NOTES (excerpt): {report.get('analyst_notes', '')[:400]}
""".strip()

    solution_context = f"""
SOLUTION TITLE: {solution.get('title')}
PITCH: {solution.get('pitch')}
ARCHITECTURE: {solution.get('architecture_overview')}
TECH STACK: {sol_stack}
TIMELINE: {solution.get('timeline')}
EFFORT: {solution.get('effort_score')}
VALUE: {solution.get('value_score')}
PHASES:
{sol_phases}
RISKS:
{sol_risks}
PREREQUISITES:
{sol_prereqs}
""".strip()

    prompt = ChatPromptTemplate.from_messages([
        ("system", """You are a senior technical writer at a custom software development agency.
Write a compelling, specific, professional project proposal using the client intelligence
and solution design provided.

Rules:
- Be specific — reference actual signals from the client's website, not generic statements
- Write for both technical and business audiences (executive summary = business, architecture = technical)
- Be honest about timelines and effort — do not over-promise
- Every section must feel tailored to THIS client, not copy-paste boilerplate
- Use professional but direct language — no buzzword soup
"""),
        ("human", """Generate a complete proposal for this client and solution.

CLIENT INTELLIGENCE REPORT:
{report}

PROPOSED SOLUTION:
{solution}

Fill in all 13 proposal sections. Make it specific, evidence-based, and compelling.""")
    ])

    chain = prompt | structured_llm

    print("[Proposal Agent] Generating proposal content (one structured LLM call)...")
    content: ProposalContent = chain.invoke({
        "report": report_context,
        "solution": solution_context,
    })

    print(f"[Proposal Agent] Content generated: '{content.project_title}'")
    return content
